[build]
builder = "dockerfile"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 600
restartPolicyType = "always"
startCommand = "uvicorn server:app --host 0.0.0.0 --port $PORT --timeout-keep-alive 75"
